name: amanbox
description: تطبيق امان بوكس 2030 - تطبيق الأمان الشامل
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  flutter_blue_plus: ^1.32.12
  sensors_plus: ^4.0.2
  flutter_background_service: ^5.0.5
  permission_handler: ^11.3.0
  telephony: ^0.2.0
flutter:
  uses-material-design: true
